In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size= 0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [5]:
rf = RandomForestClassifier(n_estimators= 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

0.9611111111111111

In [10]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9833333333333333

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [16]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

0.9232053422370617
0.9666110183639399
0.9365609348914858
0.9415692821368948
0.9816360601001669
0.9565943238731218
0.9148580968280468
0.9549248747913188
0.9298831385642737


In [21]:
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators= 40), X_train, X_test, y_train, y_test))

In [22]:
scores_l

[0.9232053422370617,
 0.9415692821368948,
 0.9148580968280468,
 0.9232053422370617,
 0.9415692821368948,
 0.9148580968280468]

In [23]:
scores_svm

[0.9666110183639399,
 0.9816360601001669,
 0.9549248747913188,
 0.9666110183639399,
 0.9816360601001669,
 0.9549248747913188]

In [24]:
scores_rf

[0.9449081803005008,
 0.9549248747913188,
 0.9248747913188647,
 0.9398998330550918,
 0.9499165275459098,
 0.9131886477462438]

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85555556, 0.75555556, 0.87465181, 0.88857939, 0.85793872])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target)

array([0.91111111, 0.89722222, 0.94707521, 0.9637883 , 0.8913649 ])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92777778, 0.90833333, 0.94986072, 0.95821727, 0.90807799])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.93888889, 0.92222222, 0.95543175, 0.97214485, 0.9275766 ])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=80), digits.data, digits.target)

array([0.93611111, 0.91666667, 0.95543175, 0.97214485, 0.93314763])